#!/usr/bin/env bash

su - minecraft
echo "Removing old JARs"
find ../. -maxdepth 1 -name "*.jar" -exec rm -f {} \;
echo "Fetching latest BuildTools version"
curl -o ../BuildTools.jar "https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar";
echo "Removing old directories generated by BuildTools"
find ../. -maxdepth 1 -name "apache-maven-*" -exec rm -rf {} \;
rm -rf ../BuildData/;
rm -rf ../Bukkit/;
rm -rf ../CraftBukkit/;
rm -rf ../Spigot/;
rm -rf ../work/;

echo "Updating and building the latest Spigot Revision"
cd ..;
java -jar BuildTools.jar --rev latest;